name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build-clang:
    runs-on: macos-latest

    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Print compiler version
      run: ${{ env.CC }} --version

    - name: Install automake
      run: |
        brew update
        brew install automake

    - name: Install zimg
      run: |
        git clone https://github.com/sekrit-twc/zimg --depth 1 --shallow-submodules --recurse-submodules
        pushd zimg
        ./autogen.sh
        ./configure
        make -j3
        sudo make install -j3
        popd
        rm -rf zimg

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: '3.11'

    - name: Set PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=$pythonLocation/lib/pkgconfig" >> $GITHUB_ENV

    - name: Install/upgrade required Python packages
      run: |
        python -m pip install -U pip
        pip install -U cython setuptools wheel

    - name: configure
      run: |
        ./autogen.sh
        ./configure

    - name: make
      run: make -j3

    - name: make install
      run: |
        sudo make install -j3
        pip install .

    - name: Run test
      run: python -m unittest discover -s test -p "*test.py"
